apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  alertmanager.yml: |
    global: 
      resolve_timeout: 5m
      smtp_require_tls: true
      smtp_smarthost: 'smtp.163.com:994'
      smtp_from: 'bvaccc@163.com'
      smtp_auth_username: 'bvaccc@163.com'
      smtp_auth_password: 'Dara6unahcho'
    receivers:
    - name: carl
      email_configs:
      - to: 'bvac@qq.com'
    route:
      group_by: ['alertname']
      group_interval: 5m
      group_wait: 10s
      receiver: carl
      repeat_interval: 3h
