apiVersion: v1
kind: ConfigMap
metadata:
  name: rules
  namespace: kube-system
data:
  my.rules: |
    groups:
    - name: example
      rules:
      # - alert: HighCPU
      #   expr: (100 - (avg by (instance) (irate(node_cpu{name="node-exporter",mode="idle"}[5m])) * 100)) > 75
      #   for: 2m
      #   labels:
      #     severity: page
      #   annotations:
      #     summary: "{{$labels.instance}}: High CPU usage detected"
      #     description: "{{$labels.instance}}: CPU usage is above 75% (current value is: {{ $value }})"
      - alert: instanceDOWN
        expr: sum(up) < 13
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
