apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: carl
data:
  default.conf: |-
            server {
                listen       80;
                server_name  carl-k8s.leapstack.cn;

                client_max_body_size 8M;

                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;

                gzip  on;
                gzip_min_length 10k;
                gzip_buffers  4 64k;
                gzip_http_version 1.1;
                gzip_comp_level 3;
                gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

                resolver 10.96.0.10;
                set $bc_gw  http://bc-gw.hcp.svc.cluster.local:10102;
                set $winterfell http://winterfell.hcp.cluster.local:10901;
                set $hcp_be http://hcp-be.hcp.cluster.local:10701;

                location / {
                  root   /usr/share/nginx/html;
                  index  index.html;
                }

                error_page   500 502 503 504  /50x.html;
                location = /50x.html {
                  root   html;
                }

                location /gw/ {
                  rewrite ^/gw/(.*) /$1 break;
                  proxy_pass $bc_gw;
                  proxy_redirect http:// $scheme://;
                }

                location  /winterfell/ {
                  rewrite ^/winterfell/(.*) /$1 break;
                  proxy_pass $winterfell;
                }

                location /hcp/ {
                  rewrite ^/hcp/(.*) /$1 break;
                  proxy_pass $hcp_be;
                }
             }
