{
 "title": "HCP-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "staging",
    "query": "label_values(node_boot_time_seconds{group=\"hcp\"}, stage)"
   },
   {
    "name": "instance",
    "query": "label_values(node_boot_time_seconds{group=\"hcp\",stage=\"$staging\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(node_load1{job=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "max(node_load5{job=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "max(node_load15{job=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Usage Per Core",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\", instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Utilizaion",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\", instance=\"$instance\"}[2m])) * 100\n",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum (irate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\", instance=\"$instance\"}[2m]))) * 100\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$instance\"}\n  - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance\"}\n  - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$instance\"}\n  - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$instance\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "max(node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "mem %commit",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(node_memory_Committed_AS_bytes{instance=\"$instance\"}) / max(node_memory_MemTotal_bytes{instance=\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$instance\"}\n    - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance\"}\n    - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$instance\"}\n    - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$instance\"}\n    )\n    / node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$instance\"}\n  ) * 100)\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"$instance\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"$instance\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "max(rate(node_disk_io_time_seconds_total{job=\"node-exporter\",  instance=\"$instance\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space avail",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(node_filesystem_avail_bytes{instance=\"$instance\",mountpoint=\"/\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"$instance\", device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"$instance\", device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}