{
 "title": "kube-state-metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "持久化存储",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_spec_volumes_persistentvolumeclaims_info"
    }
   ]
  },
  {
   "title": "节点状态错误",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",status!=\"true\"}==1",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "pod restart times",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total>0"
    }
   ]
  },
  {
   "title": "count pod restart in 30m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total[30m])>0",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "total running pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running)"
    }
   ]
  },
  {
   "title": "total ready pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready)"
    }
   ]
  },
  {
   "title": "total terminated pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated==1)"
    }
   ]
  }
 ]
}